on:
  push:
  schedule:
    - cron: '0 0 * * * '

jobs:
  update-lottery-results:
    runs-on: ubuntu-latest
    name: A job to update lottery-results
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update lottery results
        uses: ./
        id: update-lottery-results
