on:
  push:
  schedule:
    - cron: '0 21 23 8 * '

jobs:
  update-lottery-results:
    runs-on: ubuntu-latest
    name: A job to update lottery-results
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: actions/setup-node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: "13.9.0"
      - name: npm install
        uses: jaid/action-npm-install@v1.2.1
      - name: Update lottery results
        uses: ./
        id: update-lottery-results
      - name: Install dependencies
        run: npm install
